
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package org.ifn660.jflexer;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RBRACK = 17;
  public static final int ELSE = 27;
  public static final int CLASS = 25;
  public static final int SEMICOLON = 19;
  public static final int PLUS = 11;
  public static final int INT = 22;
  public static final int RBRACE = 15;
  public static final int RPAREN = 13;
  public static final int PRIVATE = 5;
  public static final int LBRACK = 16;
  public static final int IDENTIFIER = 8;
  public static final int IF = 26;
  public static final int LPAREN = 12;
  public static final int LBRACE = 14;
  public static final int PUBLIC = 4;
  public static final int STRING_LITERAL = 3;
  public static final int BOOLEAN = 23;
  public static final int COMMA = 20;
  public static final int PROTECTED = 6;
  public static final int EOF = 0;
  public static final int BREAK = 18;
  public static final int DOT = 21;
  public static final int error = 1;
  public static final int EQ = 9;
  public static final int ABSTRACT = 7;
  public static final int INTEGER_LITERAL = 2;
  public static final int EQEQ = 10;
  public static final int UNKNOWN = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER_LITERAL",
  "STRING_LITERAL",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "ABSTRACT",
  "IDENTIFIER",
  "EQ",
  "EQEQ",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "BREAK",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "INT",
  "BOOLEAN",
  "UNKNOWN",
  "CLASS",
  "IF",
  "ELSE"
  };
}

