
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package org.ifn660.jflexer;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 58;
  public static final int SHORT = 9;
  public static final int CONST = 5;
  public static final int CHAR = 4;
  public static final int STRICTFP = 44;
  public static final int CASE = 24;
  public static final int DOUBLE = 6;
  public static final int LPAREN = 59;
  public static final int PRIVATE = 29;
  public static final int CONTINUE = 33;
  public static final int INTERFACE = 13;
  public static final int INT = 2;
  public static final int FOR = 23;
  public static final int ASSERT = 31;
  public static final int RPAREN = 60;
  public static final int INSTANCEOF = 40;
  public static final int STATIC = 18;
  public static final int SEMICOLON = 65;
  public static final int COMMA = 66;
  public static final int THROW = 51;
  public static final int CLASS = 11;
  public static final int PLUS = 56;
  public static final int IF = 19;
  public static final int THIS = 46;
  public static final int DOT = 67;
  public static final int ABSTRACT = 10;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 27;
  public static final int TRANSIENT = 47;
  public static final int NEW = 42;
  public static final int SUPER = 12;
  public static final int error = 1;
  public static final int EQEQ = 55;
  public static final int TRY = 50;
  public static final int NULL = 17;
  public static final int UNKNOWN = 68;
  public static final int BREAK = 26;
  public static final int VOID = 16;
  public static final int EQ = 54;
  public static final int FINALLY = 37;
  public static final int LBRACK = 63;
  public static final int SWITCH = 25;
  public static final int BYTE = 32;
  public static final int IMPORT = 39;
  public static final int LBRACE = 61;
  public static final int NATIVE = 41;
  public static final int ELSE = 20;
  public static final int PROTECTED = 30;
  public static final int RBRACK = 64;
  public static final int ENUM = 35;
  public static final int PACKAGE = 43;
  public static final int GOTO = 38;
  public static final int FINAL = 36;
  public static final int WHILE = 22;
  public static final int DEFAULT = 34;
  public static final int FLOAT = 7;
  public static final int PUBLIC = 28;
  public static final int RBRACE = 62;
  public static final int EXTENDS = 14;
  public static final int LONG = 8;
  public static final int VOLATILE = 48;
  public static final int THROWS = 52;
  public static final int SYNCHRONIZED = 45;
  public static final int IMPLEMENTS = 15;
  public static final int DO = 21;
  public static final int INTEGER_LITERAL = 57;
  public static final int IDENTIFIER = 53;
  public static final int CATCH = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "BOOLEAN",
  "CHAR",
  "CONST",
  "DOUBLE",
  "FLOAT",
  "LONG",
  "SHORT",
  "ABSTRACT",
  "CLASS",
  "SUPER",
  "INTERFACE",
  "EXTENDS",
  "IMPLEMENTS",
  "VOID",
  "NULL",
  "STATIC",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "CASE",
  "SWITCH",
  "BREAK",
  "RETURN",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "ASSERT",
  "BYTE",
  "CONTINUE",
  "DEFAULT",
  "ENUM",
  "FINAL",
  "FINALLY",
  "GOTO",
  "IMPORT",
  "INSTANCEOF",
  "NATIVE",
  "NEW",
  "PACKAGE",
  "STRICTFP",
  "SYNCHRONIZED",
  "THIS",
  "TRANSIENT",
  "VOLATILE",
  "CATCH",
  "TRY",
  "THROW",
  "THROWS",
  "IDENTIFIER",
  "EQ",
  "EQEQ",
  "PLUS",
  "INTEGER_LITERAL",
  "STRING_LITERAL",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "UNKNOWN"
  };
}

