package org.ifn660.jflexer.type;

public enum TokenType {
    ABSTRACT, BOOLEAN, BREAK, IDENTIFIER, INTEGER_LITERAL, 
    EQ, EQEQ, PLUS, STRING_LITERAL, EOF, UNKNOWN, IF, LPAREN,
    RPAREN, LBRACE, RBRACE, LBRACK, RBRACK, SEMICOLON, COMMA,
    DOT;
}
